import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const euclidFont = localFont({
  src: [
    {
      path: '../public/EuclidCircularB-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/EuclidCircularB-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/EuclidCircularB-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--font-euclid',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${euclidFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
